import "./globals.css";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import iransans from "@/public/assets/fonts/IranSans/iransans";
import { ReduxProvider } from "@/redux/provider";
import Header from "@/components/common/header-page/Header";

export const metadata: Metadata = {
  title: "My Gray Life",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${iransans.className} font-iran`}>
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <ToastContainer
            position="top-right"
            autoClose={2500}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            bodyClassName={`${iransans.className} font-iran text-sm flex my-auto`}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
